name: Test
on:
  workflow_dispatch:
    inputs: {}

jobs:
  upload_download_delete:
    - name: Create artifact file
      run: |
        echo "just nothing" > file1.txt
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: test_file
        path: file1.txt
        
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: 'test_file'
        path: some/new/path
        
    - name: Delete artifact
      uses: ./
      with:
        name: 'test_file'
